import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
)


# ============================================================
# PATH CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parents[2]

EXPORT_DIR = BASE_DIR / "exports"

EXPORT_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# SAFE FILE NAME
# ============================================================

def create_safe_filename(query: str) -> str:
    """
    Convert research query into a safe filename.
    """

    cleaned = re.sub(
        r"[^a-zA-Z0-9\s_-]",
        "",
        query,
    )

    cleaned = re.sub(
        r"\s+",
        "_",
        cleaned.strip(),
    )

    # Keep filenames reasonably short
    cleaned = cleaned[:70]

    if not cleaned:
        cleaned = "research_report"

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")

    return f"{cleaned}_{timestamp}"


# ============================================================
# MARKDOWN EXPORT
# ============================================================

def export_markdown(
    query: str,
    report: str,
    filename_base: Optional[str] = None,
) -> str:
    """
    Save the complete research report as Markdown.

    Returns:
        Absolute path of generated Markdown file.
    """

    if filename_base is None:
        filename_base = create_safe_filename(query)

    markdown_path = EXPORT_DIR / f"{filename_base}.md"

    content = f"""# Autonomous Research Report

## Research Goal

{query}

---

{report}

---

## Report Metadata

Generated by Autonomous Research Agent.

Generated at: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

    markdown_path.write_text(
        content,
        encoding="utf-8",
    )

    return str(markdown_path.resolve())


# ============================================================
# PDF TEXT CLEANING
# ============================================================

def escape_html(text: str) -> str:
    """
    Escape characters that may break ReportLab Paragraph.
    """

    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def markdown_line_to_html(line: str) -> str:
    """
    Perform lightweight Markdown conversion for PDF output.
    """

    line = escape_html(line)

    # Bold
    line = re.sub(
        r"\*\*(.*?)\*\*",
        r"<b>\1</b>",
        line,
    )

    # Inline code
    line = re.sub(
        r"`(.*?)`",
        r"<font name='Courier'>\1</font>",
        line,
    )

    return line


# ============================================================
# PDF EXPORT
# ============================================================

def export_pdf(
    query: str,
    report: str,
    filename_base: Optional[str] = None,
) -> str:
    """
    Generate a PDF version of the research report.

    Returns:
        Absolute path of generated PDF.
    """

    if filename_base is None:
        filename_base = create_safe_filename(query)

    pdf_path = EXPORT_DIR / f"{filename_base}.pdf"

    document = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        rightMargin=45,
        leftMargin=45,
        topMargin=45,
        bottomMargin=45,
        title=query,
        author="Autonomous Research Agent",
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ResearchTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=20,
        leading=25,
        spaceAfter=20,
    )

    query_style = ParagraphStyle(
        "ResearchQuery",
        parent=styles["Heading2"],
        fontSize=13,
        leading=18,
        spaceAfter=15,
    )

    heading_style = ParagraphStyle(
        "ResearchHeading",
        parent=styles["Heading2"],
        fontSize=14,
        leading=18,
        spaceBefore=12,
        spaceAfter=8,
    )

    subheading_style = ParagraphStyle(
        "ResearchSubheading",
        parent=styles["Heading3"],
        fontSize=12,
        leading=16,
        spaceBefore=10,
        spaceAfter=6,
    )

    body_style = ParagraphStyle(
        "ResearchBody",
        parent=styles["BodyText"],
        fontSize=10,
        leading=15,
        spaceAfter=7,
    )

    bullet_style = ParagraphStyle(
        "ResearchBullet",
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-8,
    )

    story = []

    # --------------------------------------------------------
    # TITLE
    # --------------------------------------------------------

    story.append(
        Paragraph(
            "Autonomous Research Report",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "<b>Research Goal</b>",
            query_style,
        )
    )

    story.append(
        Paragraph(
            escape_html(query),
            body_style,
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    # --------------------------------------------------------
    # REPORT BODY
    # --------------------------------------------------------

    lines = report.splitlines()

    for raw_line in lines:

        line = raw_line.strip()

        if not line:
            story.append(
                Spacer(1, 0.08 * inch)
            )
            continue

        # Main heading
        if line.startswith("## "):

            heading = line[3:].strip()

            story.append(
                Paragraph(
                    markdown_line_to_html(heading),
                    heading_style,
                )
            )

            continue

        # Smaller heading
        if line.startswith("### "):

            heading = line[4:].strip()

            story.append(
                Paragraph(
                    markdown_line_to_html(heading),
                    subheading_style,
                )
            )

            continue

        # Top-level Markdown title
        if line.startswith("# "):

            heading = line[2:].strip()

            story.append(
                Paragraph(
                    markdown_line_to_html(heading),
                    heading_style,
                )
            )

            continue

        # Bullet
        if line.startswith("- "):

            bullet = line[2:].strip()

            story.append(
                Paragraph(
                    f"• {markdown_line_to_html(bullet)}",
                    bullet_style,
                )
            )

            continue

        # Numbered item
        if re.match(r"^\d+\.\s", line):

            story.append(
                Paragraph(
                    markdown_line_to_html(line),
                    bullet_style,
                )
            )

            continue

        # Horizontal divider
        if line in {"---", "***", "___"}:
            story.append(
                Spacer(1, 0.15 * inch)
            )
            continue

        # Normal paragraph
        story.append(
            Paragraph(
                markdown_line_to_html(line),
                body_style,
            )
        )

    # --------------------------------------------------------
    # METADATA
    # --------------------------------------------------------

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            "<b>Report Metadata</b>",
            heading_style,
        )
    )

    generated_time = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    story.append(
        Paragraph(
            f"Generated by Autonomous Research Agent<br/>"
            f"Generated at: {generated_time}",
            body_style,
        )
    )

    document.build(story)

    return str(pdf_path.resolve())


# ============================================================
# EXPORT COMPLETE REPORT
# ============================================================

def export_report(
    query: str,
    report: str,
    generate_pdf: bool = False,
):
    """
    Export one research run.

    Markdown and PDF use the SAME filename base.

    Example:

    exports/
        AI_agents_20260927_103500.md
        AI_agents_20260927_103500.pdf
    """

    filename_base = create_safe_filename(query)

    markdown_path = export_markdown(
        query=query,
        report=report,
        filename_base=filename_base,
    )

    pdf_path = None

    if generate_pdf:
        pdf_path = export_pdf(
            query=query,
            report=report,
            filename_base=filename_base,
        )

    return {
        "markdown_path": markdown_path,
        "pdf_path": pdf_path,
        "filename_base": filename_base,
    }